import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, within } from 'storybook/test';
import { Checkbox, selectionSizes } from '@cometal/react';
import { ComponentCodeExample } from './ComponentCodeExample';

const SOURCE_URL = 'https://github.com/cometal-design/cometal-design-system/blob/main/packages/react/src/Selection/Selection.tsx';

function OverviewPage() { return <main className="ds-component-page"><header className="ds-component-hero"><div><span className="ds-eyebrow">COMPONENT · WEB · IN REVIEW</span><h1>Checkbox</h1><p>Независимый выбор с unchecked, checked и mixed. Label обязателен и входит в кликабельную область.</p></div><a href="https://www.figma.com/design/KKNGucImxFAtQLBhPy8tLs?node-id=1571-521" target="_blank" rel="noreferrer">Открыть в Figma ↗</a></header><section className="ds-component-section"><div className="ds-component-section__intro"><span>01</span><div><h2>Значения</h2><p>Mixed используется для родительского выбора с частично выбранными потомками.</p></div></div><div className="ds-selection-values"><article><code>Unchecked</code><Checkbox label="Согласен с условиями" description="Дополнительное пояснение выбора" /></article><article><code>Checked</code><Checkbox label="Согласен с условиями" description="Дополнительное пояснение выбора" defaultChecked /></article><article><code>Mixed</code><Checkbox label="Выбрать все строки" description="Выбрана часть строк" indeterminate /></article><article><code>Disabled</code><Checkbox label="Недоступный выбор" disabled /></article></div></section><section className="ds-component-section"><div className="ds-component-section__intro"><span>02</span><div><h2>Размеры</h2><p>Control: L 20px, M 16px, S 14px.</p></div></div><div className="ds-selection-sizes">{selectionSizes.map(size=><article key={size}><code>{size.toUpperCase()}</code><Checkbox size={size} label="Выбранный пункт" defaultChecked /></article>)}</div></section><section className="ds-component-section"><div className="ds-component-section__intro"><span>03</span><div><h2>Код</h2><p>Установка, импорт и минимальный рабочий пример соответствуют нативному checkbox API.</p></div></div><ComponentCodeExample componentId="selection.checkbox" componentName="Checkbox" sourceHref={SOURCE_URL} /></section></main>; }
const meta = { title: 'Components/Checkbox', component: Checkbox, args: { label: 'Согласен с условиями', description: 'Дополнительное пояснение выбора', size: 'l' }, argTypes: { size: { control: 'inline-radio', options: selectionSizes }, indeterminate: { control: 'boolean' } } } satisfies Meta<typeof Checkbox>;
export default meta; type Story = StoryObj<typeof meta>;
export const Overview: Story = { name: 'Обзор', parameters: { layout: 'fullscreen', controls: { disable: true } }, render: () => <OverviewPage />, play: async ({ canvasElement }) => { await expect(canvasElement.querySelector('[data-code-example="selection.checkbox"] pre')).toHaveTextContent('<Checkbox'); } };
export const Playground: Story = { name: 'Песочница', play: async ({ canvasElement }) => { const checkbox=within(canvasElement).getByRole('checkbox',{name:/Согласен/}); await expect(checkbox).toBeEnabled(); } };
