import type { Metadata } from 'next';
import { InlineLink } from '@cometal/react';
import { CodeExample } from '../../../components/code-example';
import { ComponentEnvironmentNotes } from '../../../components/component-environment-notes';
import { SectionHeading } from '../../../components/section-heading';
import { TableFamilyHeader } from '../../../components/table-family-header';
import { TablePaginatorExample, TableSourceExample } from '../../../components/table-source-example';
import { usageExamples } from '../../../lib/usage-examples';
import { tableDocumentationSections, tablePrimitiveGeometry, tableSourceFamilies, tableStandaloneSources, tableTypographyMatrix } from '../../../lib/table-documentation';

export const metadata: Metadata = { title: 'Table' };
export default function TablePage() {
  return <main className="content-page component-detail table-family-page"><TableFamilyHeader activeHref="/components/table/" />
    <div className="metadata-strip" data-component-phase="identity" data-top-divider data-bottom-divider><span>Stable ID</span><code>data-display.table</code><span>React</span><strong>Table family</strong></div>
    <section className="content-section" data-component-phase="overview"><SectionHeading title="Read table" description="Таблица чтения подсвечивает строку целиком и не переводит отдельную ячейку в active/editing. Правый клик открывает системное меню строки." /><TableSourceExample mode="read" /><SectionHeading title="Edit table" description="Таблица редактирования подсвечивает отдельную ячейку; клик, Enter или F2 переводит доступное значение в системное поле редактирования. Drag handle меняет порядок строк." /><TableSourceExample mode="edit" /><TablePaginatorExample /></section>
    <section className="content-section" data-component-phase="visual-contract" id="states"><SectionHeading title="Матрица density и состояний" description="Обзор показывает Compact Read без filter row; полный executable matrix cells, headers, columns и paginator доступен в дочерних разделах family." /><TableSourceExample density="compact" filters={false} mode="read" /><div className="definition-list"><article><span>01</span><strong>Density</strong><p><code>comfortable | compact</code> задаётся на Table и синхронно меняет всю композицию.</p></article><article><span>02</span><strong>Interaction mode</strong><p><code>read</code> даёт row hover; <code>edit</code> даёт cell hover и controlled edit entry.</p></article><article><span>03</span><strong>Interactive states</strong><p>Sort, selection, filter operators, row context menu, current page и disabled края документируются в Headers и Paginator.</p></article></div><SectionHeading title="Проверяемая геометрия controls" description="Каждый служебный control использует реальный @cometal/react primitive и точный Figma source; размеры ниже измеряются на rendered DOM." /><div className="definition-list">{tablePrimitiveGeometry.map(([label, geometry, source], index) => <article key={label}><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong><p>{geometry} · <InlineLink href={source} target="_blank" rel="noreferrer">Figma source ↗</InlineLink></p></article>)}</div><SectionHeading title="Типографическая матрица" description="Typography одинакова в Comfortable и Compact; вложенные system controls сохраняют собственные контракты и не выравниваются стилями Table." /><div className="definition-list">{tableTypographyMatrix.map(([label, typography, source], index) => <article key={label}><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong><p>{typography} · <InlineLink href={source} target="_blank" rel="noreferrer">Figma source ↗</InlineLink></p></article>)}</div></section>
    <section className="content-section"><SectionHeading title="16 source families" description="Каждое утверждённое семейство видно и связано с точным Figma source. Количество variants — evidence покрытия, а не React props." /><div className="table-source-catalog">{tableSourceFamilies.map(([id, label, variants, source]) => <article key={id}><code>{id}</code><h3>{label}</h3><p>{variants} variants</p><InlineLink href={source} target="_blank" rel="noreferrer">Figma source ↗</InlineLink></article>)}</div></section>
    <section className="content-section"><SectionHeading title="5 standalone sources" description="File Content, Drag Handle Icon, Paginator и два utility headers остаются самостоятельными Figma sources и не подменяют Component Sets в счётчике." /><div className="table-source-catalog">{tableStandaloneSources.map(([id, label, source]) => <article key={id}><code>{id}</code><h3>{label}</h3><p>Standalone source</p><InlineLink href={source} target="_blank" rel="noreferrer">Figma source ↗</InlineLink></article>)}</div></section>
    <section className="content-section"><SectionHeading title="Разделы" description="Монстрозный компонент не превращается в плоский каталог: Cells, Headers, Columns и Paginator документируются внутри family." /><div className="definition-list">{tableDocumentationSections.map(([label, description], index) => <article key={label}><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong><p>{description}</p></article>)}</div></section>
    <section className="content-section" data-component-phase="code"><SectionHeading title="Код" description="Минимальный API сохраняет нативную семантику и не копирует Figma variants один-к-одному." /><CodeExample componentName="Table" sourceHref="https://github.com/cometal-design/cometal-design-system/blob/main/packages/react/src/Table/Table.tsx" usage={usageExamples['data-display.table']} /></section>
    <section className="content-section" data-component-phase="usage" id="usage"><SectionHeading title="Использование" description="Table представляет структурированные данные с устойчивыми отношениями между columns и rows." /><div className="guidance"><article data-tone="positive"><strong>Используйте</strong><p>Для сравнения нескольких атрибутов, сортировки, фильтрации, выбора строк и итогов в одном наборе данных.</p></article><article data-tone="negative"><strong>Не используйте</strong><p>Не используйте Table как layout grid, для короткого списка одного свойства или когда карточки лучше выражают независимые сущности.</p></article></div></section>
    <section className="content-section" data-component-phase="behavior-a11y"><SectionHeading title="Поведение и доступность" description="Нативная table-семантика связывает headers, rows и cells; интерактивные controls сохраняют собственный keyboard focus." /><div className="definition-list"><article><span>01</span><strong>Keyboard</strong><p>Scrollable region получает tab-stop и aria-label. Для reorder ручка поднимает строку по Space/Enter, стрелки меняют позицию, повторное нажатие завершает перенос.</p></article><article><span>02</span><strong>Pointer</strong><p>Строка перетаскивается только за drag handle; активная строка выделяется, а линия до или после целевой строки показывает точку вставки.</p></article><article><span>03</span><strong>Column pinning</strong><p>Пункт «Закрепить слева» переключается на «Открепить слева». Несколько колонок стыкуются по фактическим ширинам в DOM-порядке и остаются у края horizontal scroll.</p></article><article><span>04</span><strong>ARIA</strong><p>Sort сообщает aria-sort, current page — aria-current, error/disabled cells — aria-invalid/aria-disabled; reorder сопровождается polite live announcement.</p></article></div></section>
    <section className="content-section" data-component-phase="public-api" id="api"><SectionHeading title="React API" description="Table использует нативные table primitives; child components расширяют соответствующие HTML attributes и не создают parallel grid API." /><div className="api-table"><div className="api-table__head"><span>Prop / component</span><span>Тип</span><span>Назначение</span></div><div><code>Table.mode</code><code>read | edit</code><span>Row-level либо cell-level interaction model.</span></div><div><code>Table.density</code><code>comfortable | compact</code><span>Общая плотность; default comfortable.</span></div><div><code>Table.pinnedColumnIds</code><code>readonly string[]</code><span>Controlled набор закреплённых колонок.</span></div><div><code>Table.onPinnedColumnIdsChange</code><code>(ids) =&gt; void</code><span>Возвращает IDs в текущем DOM/визуальном порядке.</span></div><div><code>Table.columnWidths</code><code>Record&lt;string, number&gt;</code><span>Controlled ширины колонок в пикселях.</span></div><div><code>Table.onColumnWidthsChange</code><code>(widths) =&gt; void</code><span>Сохраняет resize между render, density и pin/unpin.</span></div><div><code>columnId</code><code>string</code><span>Связывает header, filter, body и summary одной колонки.</span></div><div><code>TableHeaderCell.resizable</code><code>boolean</code><span>Отключает resize separator для отдельной data-колонки.</span></div><div><code>TableColumnPinAction</code><code>columnId</code><span>Системная pin/unpin команда для Context Menu.</span></div><div><code>Table.rowContextMenu</code><code>(rowId) =&gt; ReactNode</code><span>Системное pointer-anchored меню по правому клику строки.</span></div><div><code>Table.onRowReorder</code><code>(event) =&gt; void</code><span>Controlled callback с activeId, overId и before/after.</span></div><div><code>TableRow.rowId</code><code>string</code><span>Стабильный ID для row menu и связанных действий.</span></div><div><code>TableRow.reorderId</code><code>string</code><span>Стабильный бизнес-ID строки для pointer и keyboard reorder.</span></div><div><code>TableFilterCell.action</code><code>ReactNode</code><span>Слот для TableFilterAction с Figma filter icon 12px.</span></div><div><code>TableCell.editable</code><code>boolean</code><span>Разрешает controlled edit entry только в mode=edit.</span></div><div><code>reorderTableRows</code><code>utility</code><span>Иммутабельно применяет reorder event к consumer-owned данным.</span></div><div><code>TablePaginator</code><code>page, pageCount, callbacks</code><span>Controlled pagination и optional page-size.</span></div></div></section>
    <div data-component-phase="adaptation"><ComponentEnvironmentNotes responsive="Table сохраняет нативную структуру внутри .cometal-table-scroll с горизонтальным overflow и именованным tab-stop; на узком viewport она не превращается в карточки автоматически." theme="Surface, border, text, selected, error и focus states используют semantic tokens активной темы; отдельного light/dark prop нет." edgeCases="Empty dataset, loading и product error принадлежат окружающей композиции; длинные значения используют column overflow policy, а disabled/error cells сохраняют aria-disabled/aria-invalid." /></div>
  </main>;
}
