import type { Metadata } from 'next';
import { CodeExample } from '../../../components/code-example';
import { ComponentEnvironmentNotes } from '../../../components/component-environment-notes';
import { ComponentPageHeader } from '../../../components/component-page-header';
import { SectionHeading } from '../../../components/section-heading';
import { WidgetSourceExample } from '../../../components/widget-source-example';
import { components, statusLabels } from '../../../lib/registry';
import { usageExamples } from '../../../lib/usage-examples';

export const metadata: Metadata = { title: 'Widget' };
const widget = components.find((item) => item.id === 'template.widget')!;

export default function WidgetPage() {
  return <main className="content-page component-detail">
    <ComponentPageHeader eyebrow="КОМПОНЕНТ · WEB" title="Widget" summary="Универсальная оболочка: title, optional description, consumer-owned toolbar и content slot. Widget не знает, что будет вложено внутрь." status={widget.status} statusLabel={statusLabels[widget.status]} figmaHref={widget.links.figma} playgroundHref="/storybook/?path=/story/components-widget--playground" />
    <div className="metadata-strip" data-top-divider data-bottom-divider><span>Stable ID</span><code>template.widget</code><span>React</span><strong>Widget</strong></div>
    <section className="content-section" id="usage"><SectionHeading title="Использование" description="Widget группирует один именованный функциональный блок и оставляет состояние вложенному payload." /><div className="guidance"><article data-tone="positive"><strong>Используйте</strong><p>Для самостоятельного named region с title, optional description, consumer-owned toolbar и одним содержательным slot.</p></article><article data-tone="negative"><strong>Не используйте</strong><p>Не используйте Widget как универсальную карточку, Table wrapper или product state machine; loading, empty и error принадлежат вложенному контенту.</p></article></div></section>
    <section className="content-section"><SectionHeading title="Main Component" description="Raised surface и 32 px radius принадлежат Widget. Внутренний payload остаётся самостоятельным компонентом и не клипуется shell." /><WidgetSourceExample /></section>
    <section className="content-section"><SectionHeading title="Анатомия" description="Четыре структурные области не превращаются в четыре boolean props: optional regions выражаются slot API." /><div className="definition-list"><article><span>01</span><strong>Title</strong><p>Обязательное видимое и доступное имя region.</p></article><article><span>02</span><strong>Description</strong><p>Optional secondary text; отсутствует без пустого gap.</p></article><article><span>03</span><strong>Toolbar</strong><p>Consumer-owned controls в документном tab order.</p></article><article><span>04</span><strong>Content slot</strong><p>Любой утверждённый payload без Widget state machine.</p></article></div></section>
    <section className="content-section"><SectionHeading title="Geometry" description="Все значения приходят из токенов; Figma documentation width и height не являются runtime API." /><div className="metadata-strip widget-geometry-strip"><span>32 outer radius</span><span>24 inset / gap</span><span>16 header padding</span><span>8 toolbar / inner radius</span></div></section>
    <section className="content-section" id="api"><SectionHeading title="React API" description="Widget — slot composition с именованной region-семантикой; public size, variant и state axes отсутствуют." /><div className="api-table"><div className="api-table__head"><span>Prop</span><span>Тип</span><span>Назначение</span></div><div><code>title</code><code>ReactNode</code><span>Обязательный видимый heading и accessible name.</span></div><div><code>description</code><code>ReactNode</code><span>Optional supporting copy.</span></div><div><code>toolbar</code><code>ReactNode</code><span>Consumer-owned controls; <code>actions</code> — deprecated alias.</span></div><div><code>as</code><code>section | article | aside | div</code><span>Семантический root; default section.</span></div><div><code>titleId / descriptionId</code><code>string</code><span>Optional стабильные связи aria-labelledby/aria-describedby.</span></div><div><code>toolbarLabel</code><code>string</code><span>Accessible name для role=toolbar.</span></div></div></section>
    <section className="content-section"><SectionHeading title="Код" description="Публичный API сохраняет generic composition. Старый actions работает только как compatibility alias toolbar." /><CodeExample componentName="Widget" sourceHref="https://github.com/cometal-design/cometal-design-system/blob/main/packages/react/src/Widget/Widget.tsx" usage={usageExamples['template.widget']} /></section>
    <ComponentEnvironmentNotes responsive="Widget fluid по ширине и content-driven по высоте. Header и toolbar переносятся; при container width ≤560px toolbar занимает новую строку, а content сохраняет собственный overflow contract." theme="Raised surface, border, title и description используют semantic tokens активной темы; отдельного light/dark prop нет." edgeCases="Без description не остаётся пустого gap, без toolbar не создаётся toolbar region. Длинный title переносится, а empty/error/loading вложенного payload не превращаются в Widget props." />
  </main>;
}
